app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

#SERIES
series_list:
    pattern:  /series
    defaults: { _controller: AppBundle:Serie:listServiio }

series_update:
    pattern:  /series/infos
    defaults: { _controller: AppBundle:Serie:updateInfos }

series_banner:
    pattern:  /serie/banner/{id}
    defaults: { _controller: AppBundle:Serie:randomBanner }
    
series_xml:
   pattern:  /series/xml
   defaults: { _controller: AppBundle:Serie:getXmlInfo }
    
serie_view:
   pattern:  /serie/{id}
   defaults: { _controller: AppBundle:Serie:view }

#SEASON
season_list:
    pattern: /seasons
    defaults: { _controller: AppBundle:Season:listServiio }

season_update:
    pattern:  /seasons/infos
    defaults: { _controller: AppBundle:Season:updateInfos }
    
#EPISODE
episodes_list:
    pattern: /episodes
    defaults: { _controller: AppBundle:Episode:listServiio }

episode_dowloaded:
    pattern: /episodes/downloaded
    defaults: { _controller: AppBundle:Episode:downloaded }

episode_watched:
    pattern: /episodes/watched
    defaults: { _controller: AppBundle:Episode:watched }
#DOWNLOAD
download_update:
   pattern: /download/update
   defaults: { _controller: AppBundle:Download:updateDownload }

download_index:
    pattern:  /download
    defaults: { _controller: AppBundle:Download:index }
  
#UNSEEN
unseen_index:
   pattern: /unseen
   defaults: { _controller: AppBundle:Unseen:index }

#CONSOLE
console_index:
    pattern: /console
    defaults: { _controller: AppBundle:Console:index }              
    
#TEST           
series_app_tvdb:
    pattern:  /tvdb
    defaults: { _controller: AppBundle:Default:tvdb }
    
series_app_serviio:
    pattern:  /serviio
    defaults: { _controller: AppBundle:Default:serviio }

series_app_rss:
    pattern:  /rss
    defaults: { _controller: AppBundle:Default:rss }

series_app_betaseries:
    pattern:  /bs/{format}
    defaults: { _controller: AppBundle:Default:bs, format: json }
    
#SECURITY
login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Default:login }
    
login_check:
    pattern:   /login_check