<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends EntityRepository
{
    public function getUnfinsihed()
    {
        return $this->createQueryBuilder('s')
            ->where('s.remaining > 0 and s.archived = 0')
            ->getQuery()
            ->getResult();
    }
    
    
}
